### PR TITLE
Restrict choice of business process and tso codes

### PR DESCRIPTION
**Pull request by FranckLecuyer**
**Branch based on 'remove_alternative_tso' branch**

### CODE REVIEW

**Comment by FranckLecuyer** [comment]
To be merged after PR: https://github.com/gridsuite/gridmerge-app/pull/52

**Review by niconoir — APPROVED** [review]

**Review by geofjamg — COMMENTED** [review]
@FranckLecuyer Is there any reason to put this file in the public folder and not in the source?

**Review by JacquesBorsenberger — APPROVED** [review]

**Comment by FranckLecuyer** [comment]
> @FranckLecuyer Is there any reason to put this file in the public folder and not in the source?

**Comment by FranckLecuyer** [comment]
> @FranckLecuyer Is there any reason to put this file in the public folder and not in the source?

It's easier to fetch, because you have just to give the filename to the fetch method, and the same thing is done for the countries json files for the map
But, later, these files will be stored in the database and should be retrieved/modified from the merge orchestrator server web service ...

**Pull request merged**
